name: Build Script Studio

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Windows installer
        run: npm run dist

      - name: Upload Windows installer
        uses: actions/upload-artifact@v3
        with:
          name: script-studio-windows
          path: dist/**/*.exe
